import { StoreDataItemType } from 'types/StoreData.type';

export const getStoreData = async (): Promise<StoreDataItemType[]> => {
  const data = [
    {
      storeId: '1234',
      displayName: 'ABC Store',
      mapIcon: '',
      description: 'This is a popular retail store',
      isClarkStore: true,
      isAppointmentStore: false,
      storeType: 'Grocery',
      storeProfile: 'A1B2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '10:00:00 AM',
      address: '123 Main St, Anytown, USA',
    },
    {
      storeId: '5678',
      displayName: 'XYZ Store',
      mapIcon: '',
      description: 'This is a popular clothing store',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Apparel',
      storeProfile: 'C3D4',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '11:00:00 AM',
      address: '456 Oak St, Anytown, USA',
    },
    {
      storeId: '9012',
      displayName: 'LMN Store',
      mapIcon: '',
      description: 'This is a popular electronics store',
      isClarkStore: true,
      isAppointmentStore: true,
      storeType: 'Electronics',
      storeProfile: 'E5F6',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '12:00:00 PM',
      address: '789 Elm St, Anytown, USA',
    },
    {
      storeId: '3456',
      displayName: 'PQR Store',
      mapIcon: '',
      description: 'This is a popular department store',
      isClarkStore: false,
      isAppointmentStore: false,
      storeType: 'Department',
      storeProfile: 'G7H8',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '01:00:00 PM',
      address: '321 Maple St, Anytown, USA',
    },
    {
      storeId: '7890',
      displayName: 'DEF Store',
      mapIcon: '',
      description: 'This is a popular furniture store',
      isClarkStore: true,
      isAppointmentStore: false,
      storeType: 'Furniture',
      storeProfile: 'I9J0',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '02:00:00 PM',
      address: '654 Pine St, Anytown, USA',
    },
    {
      storeId: '2345',
      displayName: 'QRS Store',
      mapIcon: '',
      description: 'This is a popular pharmacy',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Pharmacy',
      storeProfile: 'K1L2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '03:00:00 PM',
      address: '987 Cedar St, Anytown, USA',
    },
    {
      storeId: '4345',
      displayName: 'QRS Store',
      mapIcon: '',
      description: 'This is a popular pharmacy',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Pharmacy',
      storeProfile: 'K1L2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '03:00:00 PM',
      address: '987 Cedar St, Anytown, USA',
    },
    {
      storeId: '2346',
      displayName: 'QRS Store',
      mapIcon: '',
      description: 'This is a popular pharmacy',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Pharmacy',
      storeProfile: 'K1L2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '03:00:00 PM',
      address: '987 Cedar St, Anytown, USA',
    },
    {
      storeId: '2347',
      displayName: 'QRS Store',
      mapIcon: '',
      description: 'This is a popular pharmacy',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Pharmacy',
      storeProfile: 'K1L2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '03:00:00 PM',
      address: '987 Cedar St, Anytown, USA',
    },
    {
      storeId: '2348',
      displayName: 'QRS Store',
      mapIcon: '',
      description: 'This is a popular pharmacy',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Pharmacy',
      storeProfile: 'K1L2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '03:00:00 PM',
      address: '987 Cedar St, Anytown, USA',
    },
    {
      storeId: '2349',
      displayName: 'QRS Store',
      mapIcon: '',
      description: 'This is a popular pharmacy',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Pharmacy',
      storeProfile: 'K1L2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '03:00:00 PM',
      address: '987 Cedar St, Anytown, USA',
    },
    {
      storeId: '2350',
      displayName: 'QRS Store',
      mapIcon: '',
      description: 'This is a popular pharmacy',
      isClarkStore: false,
      isAppointmentStore: true,
      storeType: 'Pharmacy',
      storeProfile: 'K1L2',
      geocodingTimestamp: '07/03/2023',
      geocodingTime: '03:00:00 PM',
      address: '987 Cedar St, Anytown, USA',
    },
  ];
  return data;
};
